# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamma.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgamma.proto\x12\x1cwire.readingcomprehension.v1\"\x14\n\x12StatusCheckRequest\";\n\x06Status\x12\x19\n\x11model_description\x18\x01 \x01(\t\x12\x16\n\x0emodeling_notes\x18\x02 \x01(\t\"k\n\x10QueryPassagePair\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07passage\x18\x02 \x01(\t\x12\x17\n\x0fmax_num_answers\x18\x03 \x01(\r\x12\x1b\n\x13min_score_threshold\x18\x04 \x01(\x02\"y\n\x11QueryWithPassages\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x10\n\x08passages\x18\x02 \x03(\t\x12#\n\x1bmax_num_answers_per_passage\x18\x03 \x01(\r\x12\x1b\n\x13min_score_threshold\x18\x04 \x01(\x02\"\xb7\x01\n\x0c\x46oundAnswers\x12\x41\n\x06\x61nswer\x18\x01 \x03(\x0b\x32\x31.wire.readingcomprehension.v1.FoundAnswers.Answer\x1a\x64\n\x06\x41nswer\x12\x19\n\x11start_char_offset\x18\x01 \x01(\r\x12\x17\n\x0f\x65nd_char_offset\x18\x02 \x01(\r\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x02\x12\x0c\n\x04text\x18\x04 \x01(\t\"V\n\x17\x46oundAnswersForPassages\x12;\n\x07\x61nswers\x18\x01 \x03(\x0b\x32*.wire.readingcomprehension.v1.FoundAnswers2\xeb\x02\n\x14ReadingComprehension\x12i\n\x0b\x46indAnswers\x12..wire.readingcomprehension.v1.QueryPassagePair\x1a*.wire.readingcomprehension.v1.FoundAnswers\x12\x80\x01\n\x16\x46indAnswersForPassages\x12/.wire.readingcomprehension.v1.QueryWithPassages\x1a\x35.wire.readingcomprehension.v1.FoundAnswersForPassages\x12\x65\n\x0bStatusCheck\x12\x30.wire.readingcomprehension.v1.StatusCheckRequest\x1a$.wire.readingcomprehension.v1.Statusb\x06proto3')



_STATUSCHECKREQUEST = DESCRIPTOR.message_types_by_name['StatusCheckRequest']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_QUERYPASSAGEPAIR = DESCRIPTOR.message_types_by_name['QueryPassagePair']
_QUERYWITHPASSAGES = DESCRIPTOR.message_types_by_name['QueryWithPassages']
_FOUNDANSWERS = DESCRIPTOR.message_types_by_name['FoundAnswers']
_FOUNDANSWERS_ANSWER = _FOUNDANSWERS.nested_types_by_name['Answer']
_FOUNDANSWERSFORPASSAGES = DESCRIPTOR.message_types_by_name['FoundAnswersForPassages']
StatusCheckRequest = _reflection.GeneratedProtocolMessageType('StatusCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSCHECKREQUEST,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.StatusCheckRequest)
  })
_sym_db.RegisterMessage(StatusCheckRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.Status)
  })
_sym_db.RegisterMessage(Status)

QueryPassagePair = _reflection.GeneratedProtocolMessageType('QueryPassagePair', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPASSAGEPAIR,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.QueryPassagePair)
  })
_sym_db.RegisterMessage(QueryPassagePair)

QueryWithPassages = _reflection.GeneratedProtocolMessageType('QueryWithPassages', (_message.Message,), {
  'DESCRIPTOR' : _QUERYWITHPASSAGES,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.QueryWithPassages)
  })
_sym_db.RegisterMessage(QueryWithPassages)

FoundAnswers = _reflection.GeneratedProtocolMessageType('FoundAnswers', (_message.Message,), {

  'Answer' : _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
    'DESCRIPTOR' : _FOUNDANSWERS_ANSWER,
    '__module__' : 'gamma_pb2'
    # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.FoundAnswers.Answer)
    })
  ,
  'DESCRIPTOR' : _FOUNDANSWERS,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.FoundAnswers)
  })
_sym_db.RegisterMessage(FoundAnswers)
_sym_db.RegisterMessage(FoundAnswers.Answer)

FoundAnswersForPassages = _reflection.GeneratedProtocolMessageType('FoundAnswersForPassages', (_message.Message,), {
  'DESCRIPTOR' : _FOUNDANSWERSFORPASSAGES,
  '__module__' : 'gamma_pb2'
  # @@protoc_insertion_point(class_scope:wire.readingcomprehension.v1.FoundAnswersForPassages)
  })
_sym_db.RegisterMessage(FoundAnswersForPassages)

_READINGCOMPREHENSION = DESCRIPTOR.services_by_name['ReadingComprehension']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSCHECKREQUEST._serialized_start=45
  _STATUSCHECKREQUEST._serialized_end=65
  _STATUS._serialized_start=67
  _STATUS._serialized_end=126
  _QUERYPASSAGEPAIR._serialized_start=128
  _QUERYPASSAGEPAIR._serialized_end=235
  _QUERYWITHPASSAGES._serialized_start=237
  _QUERYWITHPASSAGES._serialized_end=358
  _FOUNDANSWERS._serialized_start=361
  _FOUNDANSWERS._serialized_end=544
  _FOUNDANSWERS_ANSWER._serialized_start=444
  _FOUNDANSWERS_ANSWER._serialized_end=544
  _FOUNDANSWERSFORPASSAGES._serialized_start=546
  _FOUNDANSWERSFORPASSAGES._serialized_end=632
  _READINGCOMPREHENSION._serialized_start=635
  _READINGCOMPREHENSION._serialized_end=998
# @@protoc_insertion_point(module_scope)
